import keyMirror from 'keymirror';

export default keyMirror({
  FETCH_ENVIRONMENT_CONFIGURATION_SUCCESS: null,
  UPDATE_ENVIRONMENT_CONFIGURATION_PENDING: null,
  UPDATE_ENVIRONMENT_CONFIGURATION_SUCCESS: null
});
