import keyMirror from 'keymirror';

export default keyMirror({
  ADD_NODE: null,
  SELECT_NODE: null,
  REMOVE_NODE: null,
  UPDATE_NODE: null,
  START_NODES_REGISTRATION_PENDING: null,
  START_NODES_REGISTRATION_SUCCESS: null,
  START_NODES_REGISTRATION_FAILED: null,
  NODES_REGISTRATION_SUCCESS: null,
  NODES_REGISTRATION_FAILED: null,
  CANCEL_NODES_REGISTRATION: null
});
