import keyMirror from 'keymirror';

export default keyMirror({
  FETCH_VALIDATION_STAGES_PENDING: null,
  FETCH_VALIDATION_STAGES_SUCCESS: null,
  FETCH_VALIDATION_STAGES_FAILED: null,
  SHOW_VALIDATION_STAGE: null,
  TOGGLE_VALIDATION_STAGE_VISIBILITY: null,
  TOGGLE_SHOW_VALIDATIONS: null,
  SHOW_VALIDATIONS: null,
  UPDATE_STAGE_STATUS: null,
  UPDATE_VALIDATION_STATUS: null
});
